CREATE TABLE IF NOT EXISTS `__squirrel` (
    `_id` VARCHAR(255) NOT NULL,
    `v` TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `__squirrel_catchup` (
    `to` VARCHAR(255) NOT NULL,
    `data` JSON NOT NULL,
    `op` VARCHAR(255) NOT NULL,
    `time` BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
